config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'

  get   'tweets'      =>  'tweets#index'
  get   'tweets/new'  =>  'tweets#new'
  post  'tweets'      =>  'tweets#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :country, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all.limit(12)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.save
    redirect_to root_path, notice: 'メッセージが送信されました'
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :country, :image, :detail)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AfterHours
    %link{:href => "https://fonts.googleapis.com/css?family=Abel|Abril+Fatface|Patua+One&display=swap", :rel => "stylesheet"}/
    %link{:href => "https://use.fontawesome.com/releases/v5.6.1/css/all.css", :rel => "stylesheet"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/shared/_contents.html.haml
#contents
  #ContentsBody
    .Container
      %span.Guid
        %a#ContentsStart
      #Main
        %article.section
          .container
            %header.header.header--section
              %h2.text-middle
                .color-gray-light
                NEW TOPICS
            %ul#list-module.thumbnails
              - @tweets.each do |tweet|
                %li.col
                  = link_to "", class: "col_contents" do
                    = image_tag tweet.image.url do
                      .thumbnail_figure
                    .thumbnail__caption
                      %h3.text-xsmall.text-overflow
                        %span>
                          = tweet.country
                          ／
                          = tweet.title
      #Sub
        %aside.section
          %h4.text-small.hr-bottom--thin.no-space-bottom
            %i.icon-crown.color-gray-light>
            RANKING
          %ul.listview.listview--condensed.text-small
            %li
              .box
                .box__cell.w40.align-center
                  %p.label.bgcolor-gray-lighter.align-center
                    1
                .box__cell.pl1em
                  %p.text-xsmall.no-space
                    U.S.A.
          %ul.listview.listview--condensed.text-small
            %li
              .box
                .box__cell.w40.align-center
                  %p.label.bgcolor-gray-lighter.align-center
                    2
                .box__cell.pl1em
                  %p.text-xsmall.no-space
                    Thai
          %ul.listview.listview--condensed.text-small
            %li
              .box
                .box__cell.w40.align-center
                  %p.label.bgcolor-gray-lighter.align-center
                    3
                .box__cell.pl1em
                  %p.text-xsmall.no-space
                    Italia
          %ul.listview.listview--condensed.text-small
            %li
              .box
                .box__cell.w40.align-center
                  %p.label.bgcolor-gray-lighter.align-center
                    4
                .box__cell.pl1em
                  %p.text-xsmall.no-space
                    Canada
          %ul.listview.listview--condensed.text-small
            %li
              .box
                .box__cell.w40.align-center
                  %p.label.bgcolor-gray-lighter.align-center
                    5
                .box__cell.pl1em
                  %p.text-xsmall.no-space
                    Japan

app/views/shared/_footer.html.haml
.main_footer
  .copyright
    Copyright (C) 2019  NishidaDaiki Corporation. All Rights Reserved.

app/views/shared/_header.html.haml
.main_header
  %nav.globalnav
    .globalnav__menu
      %ul.gmenu
        %li.logo
          = link_to root_path, class: "logo-header" do
            AfterHours
        - if user_signed_in?
          %li.entry_button
            = link_to tweets_new_path,class: "newtopic-header" do
              NewTopic
        - else
          %li.entry_button
            = link_to 'Login',root_path
          %li.entry_button
            = link_to 'Sign up' ,root_path

app/views/shared/_left-contents.html.haml
#contents
  #ContentsBody
    .Container
      %span.Guid
        %a#yjContentsStart
      #Main
        %article.section
          .container
            %header.header.header--section
              %h2.text-middle
                %i.far.fa-comments.color-gray-light
                New Spots
            %ul#list-module.thumbnails
              %li.col
                = image_tag "https://cdn.zekkei-japan.jp/images/areas/40f21b30b17c649b5263113065a9e1a7.jpg" do
                  .thumbnail_figure
                .thumbnail__caption
                  %h3.text-xsmall.text-overflow
                    %span>
                      %i.icon-rate-60.text-xxsmall.opacity-60{:title => ""}
                    東京の都市伝説
              %li.col
                = image_tag "https://cdn.zekkei-japan.jp/images/areas/40f21b30b17c649b5263113065a9e1a7.jpg" do
                  .thumbnail_figure
                .thumbnail__caption
                  %h3.text-xsmall.text-overflow
                    %span>
                      %i.icon-rate-60.text-xxsmall.opacity-60{:title => ""}
                    東京の都市伝説
              %li.col
                = image_tag "https://cdn.zekkei-japan.jp/images/areas/40f21b30b17c649b5263113065a9e1a7.jpg" do
                  .thumbnail_figure
                .thumbnail__caption
                  %h3.text-xsmall.text-overflow
                    %span>
                      %i.icon-rate-60.text-xxsmall.opacity-60{:title => ""}
                    東京の都市伝説
              %li.col
                = image_tag "https://cdn.zekkei-japan.jp/images/areas/40f21b30b17c649b5263113065a9e1a7.jpg" do
                  .thumbnail_figure
                .thumbnail__caption
                  %h3.text-xsmall.text-overflow
                    %span>
                      %i.icon-rate-60.text-xxsmall.opacity-60{:title => ""}
                    東京の都市伝説
            %ul#list-module.thumbnails
              %li.col
                = image_tag "https://cdn.zekkei-japan.jp/images/areas/40f21b30b17c649b5263113065a9e1a7.jpg" do
                  .thumbnail_figure
                .thumbnail__caption
                  %h3.text-xsmall.text-overflow
                    %span>
                      %i.icon-rate-60.text-xxsmall.opacity-60{:title => ""}
                    東京の都市伝説
              %li.col
                = image_tag "https://cdn.zekkei-japan.jp/images/areas/40f21b30b17c649b5263113065a9e1a7.jpg" do
                  .thumbnail_figure
                .thumbnail__caption
                  %h3.text-xsmall.text-overflow
                    %span>
                      %i.icon-rate-60.text-xxsmall.opacity-60{:title => ""}
                    東京の都市伝説
              %li.col
                = image_tag "https://cdn.zekkei-japan.jp/images/areas/40f21b30b17c649b5263113065a9e1a7.jpg" do
                  .thumbnail_figure
                .thumbnail__caption
                  %h3.text-xsmall.text-overflow
                    %span>
                      %i.icon-rate-60.text-xxsmall.opacity-60{:title => ""}
                    東京の都市伝説
              %li.col
                = image_tag "https://cdn.zekkei-japan.jp/images/areas/40f21b30b17c649b5263113065a9e1a7.jpg" do
                  .thumbnail_figure
                .thumbnail__caption
                  %h3.text-xsmall.text-overflow
                    %span>
                      %i.icon-rate-60.text-xxsmall.opacity-60{:title => ""}
                    東京の都市伝説

app/views/tweets/index.html.haml
.main_header
  =render partial: 'shared/header'
.main_contents
  =render partial: 'shared/contents'
.main_footer
  =render partial: 'shared/footer'

app/views/tweets/new.html.haml
= render 'shared/header'
.contents.row
  .container-new
    %h3
      New Topic
    = form_for @tweet do |f|
      .item__content
        .form__group
          = f.label :Title, class: "form-label"
          %span.form-require *Mandatory field
          = f.text_field :title, class: "input__default"
      .item__content
        .form__group
          = f.label :Country, class: "form-label"
          %span.form-require *Mandatory field
          = f.text_field :country, class: "input__default"
      .item__content
        = f.fields_for :image, Tweet.new do |image|
          .form__mask
            = f.label :image, class: 'form__mask__image' do
              =f.label :image, class: "form-label"
              %span.form-require *Mandatory field
              = f.file_field :image, class: "hidden"
              .form__mask__box
      .item__content
        .form__group
          =f.label :Review, class: "form-label"
          %span.form-require *Mandatory field
          =f.text_area :detail, class: "textarea__default", rows: "7"
        = f.submit 'Send', class: 'form__submit'


= render 'shared/footer'